name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to pub.dev 🚀
        uses: k-paxian/dart-package-publisher@master
        with:
        # Pub credentials can be fount at:
        #
        # MAC: ~/Library/Application Support/dart as `pub-credentials.json`
        #
        # WINDOWS: %APPDATA%/dart/pub-credentials.json
        #
        # LINUX: $XDG_CONFIG_HOME/dart/pub-credentials.json
        #        or
        #        $HOME/.config/dart/pub-credentials.json
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          skipTests: true
          flutter: true
